shelltype: EQUIDISTANT
nrad: 5
colormap: Viridis (matplotlib)
show_axis: False
show_scalar_bar: True
display_representation: Surface
color_range_method: auto
custom_color_range: [0.0, 1.0]
view: ['-x', '-y']
geometry: [ 1440, 2560]
filetype: vtu
# output_prefix: None
scalars: ['w']
ColorBar:
  AutoOrient: 0
  Orientation: 'Horizontal'
  WindowLocation: 'Upper Center'
  Position: [0.29, 0.02]
  Title: ''
  ComponentTitle: ''
  TitleJustification: 'Centered'
  HorizontalTitle: 0
  TitleOpacity: 1.0
  TitleFontFamily: 'Courier'
  TitleFontFile: ''
  TitleBold: 0
  TitleItalic: 0
  TitleShadow: 0
  TitleFontSize: 64
  TitleColor: [0.0, 0.0, 0.0]
  LabelOpacity: 1.0
  LabelFontFamily: 'Courier'
  LabelFontFile: ''
  LabelBold: 0
  LabelItalic: 0
  LabelShadow: 0
  LabelFontSize: 64
  LabelColor: [0.0, 0.0, 0.0]
  AutomaticLabelFormat: 1
  LabelFormat: '%-#6.3g'
  DrawTickMarks: 1
  DrawTickLabels: 1
  UseCustomLabels: 0
  CustomLabels: [0.0]
  AddRangeLabels: 1
  RangeLabelFormat: '%-#6.1e'
  DrawAnnotations: 1
  AddRangeAnnotations: 0
  AutomaticAnnotations: 0
  DrawNanAnnotation: 0
  NanAnnotation: 'NaN'
  TextPosition: 'Ticks right/top, annotations left/bottom'
  ReverseLegend: 0
  ScalarBarThickness: 25
  ScalarBarLength: 0.33
